# Generated by Django 4.2.3 on 2023-07-31 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('post_no', models.AutoField(auto_created=1000, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, null=None)),
                ('content', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('image_link', models.URLField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modefied_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
